eureka:
  client:
    serviceUrl:
      defaultZone: http://admin:123456@192.168.81.181:8761/eureka/
      
server:
  port: 8768
  
spring:
  application:
    name: eshop-one-service

feign:
  hystrix:
    enabled: true